### ISSUE TITLE
Composer requires twig/twig with strict version

### ISSUE THREAD

**Issue by inmun** [cakemail/cakemail-php#2]
Twig is required with strict version 2. Can be version 3 allowed?
```
  "require": {
    "php" : ">=7.2.5",
    "twig/twig":"^2.14.0",
    "guzzlehttp/guzzle": "6.5.5"
  },
```
`
    "twig/twig":"^2.14.0 | ^3.0",
`

**Comment by hdg** [comment]
We will reach out to you as soon as our validation is completed. Thank you for your inquiry.

**Comment by demetrius-edelin** [comment]
We added this update in 1.3.4. Thank you for the suggestion.
