### ISSUE TITLE
The response object no work properly.

### ISSUE THREAD

**Issue by inmun** [cakemail/cakemail-php#3]
Hi,
I have a problem when try to get tho options on response object.
All responses that I checked have the structure similar like this:
Cakemail\Subapis::CampaignApi::schedule(): Response
`new Response($this->openApiObj->scheduleCampaignWithHttpInfo($allParams['campaign_id']['value'], $allParams['account_id']['value'], $allParams['schedule_campaign']['value']));`

The response of  [Cakemail\Lib\Api::scheduleCampaignWithHttpInfo() line 4073](https://github.com/cakemail/cakemail-php/blob/master/libs/openapi/lib/Api/CampaignApi.php#L4073) is an array, but[ \Cakemail\Response::construct()](https://github.com/cakemail/cakemail-php/blob/master/src/Response.php#L15) expect an object.
Is not possible to validate the response with this structure.

**Comment by demetrius-edelin** [comment]
Thank you for the fix. We updated the code.
